import { Head } from '@inertiajs/react';
import {
    Bot,
    CheckCircle,
    Edit3,
    Eye,
    FileText,
    MessageSquare,
    XCircle,
} from 'lucide-react';
import {
    MarkusBadge,
    MarkusButton,
    MarkusCard,
    MarkusCardContent,
    MarkusCardDescription,
    MarkusCardHeader,
    MarkusCardTitle,
} from '@/components/markus/markus-ui';
import type { Draft } from '@/types/marketing';

export default function ContentIndex({ drafts }: { drafts: Draft[] }) {
    const pending = drafts.filter((draft) => draft.status === 'Pending Review');
    const others = drafts.filter((draft) => draft.status !== 'Pending Review');

    return (
        <>
            <Head title="Content Workflow" />
            <div className="animate-in space-y-6 duration-500 fade-in slide-in-from-bottom-4">
                <div className="flex items-end justify-between">
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight text-[#E0E0E1]">
                            Content Workflow
                        </h1>
                        <p className="mt-1 text-[#6B6B76]">
                            Review and approve content generated by your agents.
                        </p>
                    </div>
                    <div className="flex gap-3">
                        <select className="rounded-md border border-[#1F1F23] bg-[#0E0E11] px-3 py-2 text-sm text-[#E0E0E1] focus:border-[#D4AF37] focus:ring-[#D4AF37]">
                            <option>All Types</option>
                            <option>Blog Posts</option>
                            <option>Social Media</option>
                            <option>Emails</option>
                        </select>
                        <MarkusButton>
                            Approve All ({pending.length})
                        </MarkusButton>
                    </div>
                </div>

                <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                    <div className="space-y-4 md:col-span-1">
                        <MarkusCard className="border-[#D4AF37]/30 shadow-sm">
                            <MarkusCardHeader className="pb-3">
                                <MarkusCardTitle className="text-lg">
                                    Approval Queue
                                </MarkusCardTitle>
                                <MarkusCardDescription>
                                    {pending.length} items need your attention
                                </MarkusCardDescription>
                            </MarkusCardHeader>
                            <MarkusCardContent className="space-y-3">
                                {pending.map((draft) => (
                                    <div
                                        key={draft.id}
                                        className="flex cursor-pointer flex-col gap-2 rounded-lg border border-[#D4AF37]/20 bg-[#D4AF37]/10 p-3"
                                    >
                                        <div className="flex items-start justify-between">
                                            <MarkusBadge
                                                variant="outline"
                                                className="bg-[#0E0E11] text-xs"
                                            >
                                                {draft.type}
                                            </MarkusBadge>
                                            <span className="text-xs text-[#6B6B76]">
                                                {draft.date}
                                            </span>
                                        </div>
                                        <h4 className="text-sm leading-snug font-semibold text-[#E0E0E1]">
                                            {draft.title}
                                        </h4>
                                        <div className="mt-1 flex items-center justify-between">
                                            <span className="flex items-center text-xs text-[#6B6B76]">
                                                <FileText className="mr-1 h-3 w-3" />{' '}
                                                {draft.agent}
                                            </span>
                                            <span className="rounded bg-emerald-500/10 px-1.5 py-0.5 text-xs font-medium text-emerald-500">
                                                Score: {draft.score}
                                            </span>
                                        </div>
                                    </div>
                                ))}

                                <h4 className="mt-6 mb-2 text-xs font-semibold tracking-wider text-[#6B6B76] uppercase">
                                    Other Drafts
                                </h4>

                                {others.map((draft) => (
                                    <div
                                        key={draft.id}
                                        className="flex cursor-pointer flex-col gap-2 rounded-lg border border-[#1F1F23] bg-[#0E0E11] p-3 opacity-75 transition-opacity hover:opacity-100"
                                    >
                                        <div className="flex items-start justify-between">
                                            <MarkusBadge
                                                variant="secondary"
                                                className="text-xs"
                                            >
                                                {draft.status}
                                            </MarkusBadge>
                                            <span className="text-xs text-[#6B6B76]">
                                                {draft.date}
                                            </span>
                                        </div>
                                        <h4 className="truncate text-sm leading-snug font-medium text-[#E0E0E1]">
                                            {draft.title}
                                        </h4>
                                    </div>
                                ))}
                            </MarkusCardContent>
                        </MarkusCard>
                    </div>

                    <div className="md:col-span-2">
                        {/* WYSIWYG Editor mockup (preserves the original layout) */}
                        <MarkusCard className="flex h-[600px] flex-col border-[#1F1F23] shadow-sm">
                            <div className="flex flex-col border-b border-[#1F1F23]">
                                <div className="flex items-center justify-between rounded-t-xl bg-[#111114]/50 p-4">
                                    <div>
                                        <div className="mb-1 flex items-center gap-2">
                                            <MarkusBadge>Blog Post</MarkusBadge>
                                            <span className="text-sm font-medium text-[#6B6B76]">
                                                Draft by Writer Agent
                                            </span>
                                            <span className="text-sm text-[#6B6B76]">
                                                • Just now
                                            </span>
                                        </div>
                                        <h2 className="text-xl font-bold text-[#E0E0E1]">
                                            How Generative AI is Changing SEO in
                                            2026
                                        </h2>
                                    </div>
                                    <div className="flex gap-2">
                                        <MarkusButton
                                            variant="outline"
                                            size="sm"
                                        >
                                            <Eye className="mr-2 h-4 w-4" />{' '}
                                            Preview
                                        </MarkusButton>
                                    </div>
                                </div>

                                <div className="flex items-center gap-1 border-t border-[#1F1F23] bg-[#0E0E11] p-2">
                                    <select className="cursor-pointer border-none bg-transparent py-1 text-sm font-medium text-[#E0E0E1] focus:ring-0">
                                        <option>Paragraph</option>
                                        <option>Heading 1</option>
                                        <option>Heading 2</option>
                                    </select>
                                    <div className="mx-2 h-4 w-px bg-[#1F1F23]" />
                                    <button className="rounded p-1.5 font-bold text-[#9A9A9E] hover:bg-[#1C1C21]">
                                        B
                                    </button>
                                    <button className="rounded p-1.5 text-[#9A9A9E] italic hover:bg-[#1C1C21]">
                                        I
                                    </button>
                                    <button className="rounded p-1.5 text-[#9A9A9E] underline hover:bg-[#1C1C21]">
                                        U
                                    </button>
                                    <div className="mx-2 h-4 w-px bg-[#1F1F23]" />
                                    <button className="flex items-center rounded p-1.5 text-sm text-[#9A9A9E] hover:bg-[#1C1C21]">
                                        <MessageSquare className="mr-1 h-3.5 w-3.5" />{' '}
                                        Comment
                                    </button>
                                    <div className="flex-1" />
                                    <div className="mr-2 flex items-center rounded bg-emerald-500/10 px-2 py-1 text-xs font-medium text-emerald-500">
                                        SEO Score: 92/100
                                    </div>
                                </div>
                            </div>

                            <div className="article-content prose prose-indigo max-w-none flex-1 overflow-y-auto bg-[#0E0E11] p-6">
                                <p className="leading-relaxed text-[#E0E0E1]">
                                    The landscape of Search Engine Optimization
                                    has fundamentally shifted. Gone are the days
                                    when keyword stuffing and superficial
                                    backlink building could secure a top spot on
                                    Google&apos;s SERPs. In 2026, the rise of{' '}
                                    <mark className="bg-[#D4AF37]/20 text-[#D4AF37]">
                                        Generative Engine Optimization (GEO)
                                    </mark>{' '}
                                    means brands must optimize not just for
                                    traditional crawlers, but for AI reasoning
                                    engines.
                                </p>

                                <h3 className="mt-6 mb-3 text-lg font-bold text-[#E0E0E1]">
                                    Understanding the AI Response Synthesis
                                </h3>

                                <p className="leading-relaxed text-[#E0E0E1]">
                                    When a user queries an AI like{' '}
                                    <span className="underline decoration-[#D4AF37]/50">
                                        ChatGPT, Claude, or Google&apos;s AI
                                        Overviews
                                    </span>
                                    , the system doesn&apos;t just retrieve a
                                    list of links. It synthesizes a definitive
                                    answer drawing from authoritative sources.
                                    To be included in this synthesis, your
                                    content must possess high informational
                                    density and be structured with clear entity
                                    relationships.
                                </p>

                                <div className="my-6 rounded-lg border border-[#D4AF37]/20 bg-[#D4AF37]/10 p-4">
                                    <p className="flex items-start gap-2 text-sm font-medium text-[#D4AF37]">
                                        <Bot className="mt-0.5 h-4 w-4 flex-shrink-0" />
                                        <span>
                                            <strong>AI Suggestion:</strong>{' '}
                                            Consider adding a bulleted list here
                                            detailing the 3 core pillars of GEO
                                            (Factuality, Structuring, Authority)
                                            to improve context retrieval by
                                            LLMs.
                                        </span>
                                    </p>
                                    <div className="mt-2 flex gap-2 pl-6">
                                        <MarkusButton
                                            size="sm"
                                            className="h-7 text-xs"
                                        >
                                            Accept
                                        </MarkusButton>
                                        <MarkusButton
                                            size="sm"
                                            variant="ghost"
                                            className="h-7 text-xs"
                                        >
                                            Dismiss
                                        </MarkusButton>
                                    </div>
                                </div>

                                <p className="leading-relaxed text-[#E0E0E1]">
                                    Startups that fail to adapt their content
                                    strategies will find themselves completely
                                    invisible in zero-click searches, which now
                                    account for over 65% of all informational
                                    queries.
                                </p>
                            </div>

                            <div className="flex items-center justify-between rounded-b-xl border-t border-[#1F1F23] bg-[#111114] p-4">
                                <div>
                                    <MarkusButton
                                        variant="ghost"
                                        className="text-red-500 hover:bg-red-500/10 hover:text-red-500"
                                    >
                                        <XCircle className="mr-2 h-4 w-4" />{' '}
                                        Reject &amp; Retry
                                    </MarkusButton>
                                </div>
                                <div className="flex gap-3">
                                    <MarkusButton variant="outline">
                                        <Edit3 className="mr-2 h-4 w-4" /> Save
                                        Draft
                                    </MarkusButton>
                                    <MarkusButton className="bg-emerald-600 text-white hover:bg-emerald-700">
                                        <CheckCircle className="mr-2 h-4 w-4" />{' '}
                                        Approve &amp; Schedule
                                    </MarkusButton>
                                </div>
                            </div>
                        </MarkusCard>
                    </div>
                </div>
            </div>
        </>
    );
}
